### ISSUE TITLE
Add analog LSTM layer

### ISSUE THREAD

**Issue by diego-plan9** [IBM/aihwkit#104]
## Description and motivation

Continuing the approach of adding new analog layers to the library that was recently tackled in #47 , it would be interesting to include an analog LSTM layer.

## Proposed solution

Follow the same approach used by the previous layer, by adding a new class that sticks to the interface of the existing [pytorch digital counterpart](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html#torch.nn.LSTM), and making use of `AnalogModuleBase` for the setting up of the tile and rest of analog-specific tweaks.

## Alternatives and other information

This issue also implies revising if other parts of the library need to be adjusted in order to support LSTM.

**Comment by maljoras** [comment]
Closed with #240
