### ISSUE TITLE
Add Windows build support

### ISSUE THREAD

**Issue by diego-plan9** [IBM/aihwkit#12]
## Description and motivation

Currently, the build system has not been checked and adjusted in order to support Windows-based systems. While in theory `cmake` should help us in the process, it has not been tested and it is likely lacking some Windows-specific adjustments. We should revise the build system in order to allow easy compilation on Windows machines as well, as well as updating the documentation accordingly if needed.

## Alternatives and other information

Travis Windows support can help in automating and verifying the changes.

**Comment by diego-plan9** [comment]
Thanks to the great effort from @filemaster in #58, as of a158e27 it should be possible to compile the library in Windows: an overview and some pointers [have been added to the documentation](https://aihwkit.readthedocs.io/en/latest/advanced_install.html#windows-experimental) as well. 

Please note we marked the support as experimental as there are still some rough edges and tweaks to be made (in particular, building with CUDA support might require additional tweaks): do not hesitate on reporting and commenting while the remaining issues are tackled.

**Comment by diego-plan9** [comment]
And again thanks to #67, it should be now possible to build the CUDA-enabled version of the library.

**Comment by Borjagodoy** [comment]
We have support to window using WSL! We therefore proceed to close this issue and add it to the documentation.
