### ISSUE TITLE
Issues on installation with latest CUDA toolkit and PyTorch

### ISSUE THREAD

**Issue by chaeunl** [IBM/aihwkit#126]
## Description
Hello,
For several reasons, I am trying to update my CUDA toolkit and NVIDIA driver. As PyTorch only supports CUDA 11.0 version, I installed PyTorch 1.8.0 by wheel. But, during installation of aihwkit, I got an error message saying that:  
```
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
CMake Error in /home/chaeunl/aihwkit/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target "cmTC_6aef9".
```

A few months ago, I also tried with PyTorch 1.8.0 and it was successful. The differences are CUDA/cuDNN/NVIDIA driver version (previously, CUDA=11.1, cuDNN=8.0.4, NVIDIA driver=455.xx). Also, I tried with the same cmd: `python setup.py install -DUSE_CUDA=ON -DRPU_CUDA_ARCHITECTURES="80"`

I confirmed that cmake, pybind11, blas, and scikit-build satisfy the conditions described in installation page. Could you let me know how to fix it?

* Pytorch version: 1.8.0.dev20210208+cu110
* Package version: -
* OS: 18.04.2
* Python version: 3.8.5
* Conda version (or N/A):
* CUDA: 11.2
* cuDNN: 8.1
* NVIDIA driver: 460.39
* VGA: RTX 3090

**Comment by diego-plan9** [comment]
Thanks for reporting as usual @chaeunl ! It seems PyTorch 1.8 is starting their release candidate publishing, but so far I could not find a non-conda GPU-enabled wheel for downloading, which would make troubleshooting easier: the good part is that it seems to be around the corner.

However, the
```
-- The CUDA compiler identification is unknown
```
line does look suspicious. Assuming you did a `make clean` to rule out artifacts of previous builds affecting the current one, would you know if under your previous setup, the cuda compiler was correctly identified by `cmake`?

**Comment by maljoras** [comment]
Closing this issue. Please reopen if problem persists
