### ISSUE TITLE
Allow .to() usage for analog layers

### ISSUE THREAD

**Issue by diego-plan9** [IBM/aihwkit#140]
## Description and motivation

Currently, the `.to()` method of analog layers is not fully functional. At the moment the recommended way of moving layers to GPU is via `.cuda()` directly. Ideally, we should support:
* moving the layers back to `cpu`
* seamless usage of `.to()` with both devices

## Proposed solution

The `.apply()` and `._apply()` methods used internally in torch for that purposes are likely to make the implementation tricky, as they are meant to recursively operate only on the layer Parameters and Buffers only.  We should evaluate whether it is feasible to fully tackle it without resorting to turning the `Tile` into a Tensor-like structure (which is likely desirable, but longer term) - as a first stage, focusing on `AnalogSequential`, where we have more control over the recursion, can be an option.

**Comment by maljoras** [comment]
This should be possible by now. We can open it again if necessary.
