### ISSUE TITLE
Suggestion on a new device class

### ISSUE THREAD

**Issue by wonjaeji** [IBM/aihwkit#170]
## Description and motivation

Hello, aligning with the issue #131 (I am currently co-working with @chaeunl ), we are trying to modify the device to have equal range. But, there are several issues to make the devices aligned in the given range while they have different slopes. So, instead of making devices lie in the same range, we are trying to make devices have equal weight (or conductance) at the given pulse regardless of their slopes. Meanwhile, we found that the device in NeuroSim (https://github.com/neurosim/DNN_NeuroSim_V2.0/blob/master/Documents/DNN%20NeuroSim%20V2.0%20User%20Manual.pdf; please refer to equations 8.1 to 8.3) has the required property. As we reformulated the original equation, we noticed that the equation can be represented by the model of `LinearStepDevice` (please refer the table below). 

In this sense, it would be helpful for us and potential users to include this type of device class by making up a sub-class of `LinearStepDevice` like `SoftBoundsDevice`. Instead of assigning `gamma` and other parameters, introducing new parameters such as `A` and `P_max` would decide the `slopes` and `scales` of the `LinearStepDevice`. The underneath figure shows an example of `P_max=1000`. 

![image](https://user-images.githubusercontent.com/80827990/111575921-c4e35400-87f2-11eb-881f-bb8bae221b49.png)

By including this type of device, we hope potential users to enjoy various types of devices. 

## Proposed solution
![DeviceModel](https://user-images.githubusercontent.com/80827990/111466266-67a1c100-8766-11eb-8491-7912515d40f1.jpg)

**Comment by maljoras** [comment]
Hi @wonjaeji:
Many thanks for this great suggestion. It is a nice table, but I think there are a few typos in the table. For the `SoftsBoundsDevice`, I get (note that `dw_down<0` and `w_min<0`) the same:

* slopes (up, down):  `- dw_up/w_max`, `- dw_down/w_min`  
* offsets (up, down): `dw_up` and `dw_down`

However, for the new suggested parameterization it seems rather (assuming the equations  `w(p)` on the right column are correct):
* slopes (up, down): `-1/A`, `-1/A`
* offsets (up down): `(w_min + B)/A`, `(w_max - B)/A`,

If one does some small calculations, one finds that if you want to specify the model by giving  `A`, `B`, and `w_min`, then you can set the parameters of the `SoftBoundsDevice` in the following way:
1. `w_max := B + w_min`
2.  `dw_min := B/A`  
3.  `up_down := 1 + 2*w_min/B` 

to get the very same behavior  (assuming you set `w_max_dtod=0, w_min_dtod=0, up_down_dtod=0 dw_min_dtod=0` as you did not specify how to do device-to-device variation in the new model parameterization). That seems relatively straightforward. 

Note that in the above `B=w_max - w_min` is the overall weight range, `w_min` the smallest value, and `1/A` the slope. So these parameters are quite intuitive, although one should make sure that `B>-w_min`, `A>0`, and `w_min < 0`. 

Altogether, one could write: 
```python
def my_device(A, B, w_min):
    """ Returns a `SoftBoundsDevice` with a new parameterization."""
    if (B < - w_min) or (A <= 0) or (w_min > 0):
        raise ValueError("Parameters do not meet constraints.")
    return SoftBoundDevice(w_max=B + w_min, dw_min=B / A, up_down=1 + 2 * w_min / B,
                           w_max_dtod=0, w_min_dtod=0, up_down_dtod=0, dw_min_dtod=0)
```

However, only 3 parameters are free, not 4 as in the original `SoftBoundsDevice` model. But given that you had in the example `w_max = -w_min`, and that in the new model the slopes are actually forced to be the same,  I guess that would be probably be enough? 

If yes, we could add a simple python dataclass on top of the `SoftBoundsDevice` that make the above simple transformation of the parameters. Note, however, that the device-to-device variation would not be directly on `A` and `B` but on the former parameters. What type of device-to-device variation would make sense for your device?

**Comment by wonjaeji** [comment]
@maljoras , thank you very much for the reply, and I want to explain further about the device.
The suggested device requires additional parameters which should be given when users create an object (compared to the  `LinearStepDevice`): `A` and `P_max`. In the column of `w=g(p)`, `A` is assumed to be positive and determines the `slope` and `dw_min` of a device. `P_max` determines the minimum pulse that is required to get `w_max` starting from `w_min` within minor margin. `B` is actually a hidden parameter which depends on `w_min`, `w_max`, `A` and `P_max` and approximate to `w_max-w_min`. To wrap up, there are 4 parameters to design the device: `w_max`, `w_min`, `A`, and `P_max`.

Following your suggestions using `SoftBoundsDevice`, I think some of the conditions might be rewritten as:
1. `w_max approx. w_min + B`
2. `dw_min := B/A`
3. `up_down := w_min/B`

which are valid if `w_max = -w_min` (`w_max>0` and `w_min<0`). However, I hope `w_min` and `w_max` are free to choose. I think the new device class can be implemented by adding input parameters `A` and `P_max` to the `LinearStepDevice`, then setting the `slopes` and `offsets ` depends on `A`, `B`, `w_min` and `w_max`.

Please refer the code below which I used to get the response curve. 
```python
import matplotlib.pyplot as plt
import numpy as np

def Device_Update(weight,pulse,w_min,w_max,A,P_max):
    
    B = (w_max - w_min) / (1 - np.exp(-P_max/A))
    dw_up = (w_min + B) / A
    dw_down = (w_max - B) / A
    
    if pulse>0:
        dw = (-1/A) * weight + dw_up
    else:
        dw =  - ((1/A) * weight - dw_down)
    return dw

N = 100
pulse_number = list(range(2*N+1))
pulse_sequence = [1]*N + [-1]*N

plt.figure(figsize=(12,10))
plt.title('Device Response', fontsize=25)

A_scn = [10,20,40,80]
for A in A_scn:
    w_max = 1
    w_min = -1
    P_max = 100
    
    weight_response = [w_min]
    w = w_min
    for pulse in pulse_sequence:
        dw = Device_Update(w,pulse,w_min,w_max,A,P_max)
        w = w + dw
        weight_response.append(w)
    plt.plot(pulse_number,weight_response, label="A={}".format(A))

plt.xlabel("Pulses (+/-)", fontsize=20)
plt.ylabel("Weight", fontsize=20)
plt.legend(loc="upper right", fontsize=15)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.show()
```

As for variations, we are under discussion. I agree that it is reasonable to add variations on the `slope` and `offset` directly.

**Comment by maljoras** [comment]
@wonjaeji, thank you for the further explanation. 

However, I still not quite understand the model definition. 
It seems to me that the model is somewhat ill-defined or the parameter names are a little confusing. `w_max` and `w_min` in the simulator refer to the *actual* maximal (or minimal) attainable weight (ie even if you give millions  of only positive pulses the weight will never be larger than `w_max`, in some models this is ensured by clipping). In the model with `P_max`, in the positive update direction, for p to infinity, it is `w(p -> infinity) = B + w_min`  which is *not* the same as `w_max` in general (if one does not assume any clipping), ie if `P_max` is freely to be chosen. That seems ill-defined. 

The model makes only sense if `B=w_max - w_min` which is the case I had in my answer above. So `P_max` is not a free parameter. Or do you mean to clip the weights at `w_max` and `w_min` additionally at a weight value which might be lower than the saturation level?

**Comment by wonjaeji** [comment]
I mistook to denote the parameters, `w_max` and `w_min`. What I wished to say is that these two parameters are pre-determined ones which I used to design the pulse response curve. So, instead of the previous notation, I am going to denote them as `range_max` and `range_min`. To be specific, if the weight of a device is initially set to be `range_min`, `w -> range_max` as  `p -> P_max` and vice versa.

To make it clear, I think we need to add 4 parameters: `P_max`, `A`,  `range_max`, `range_min`.

**Comment by maljoras** [comment]
I see. In that case, if the user provides `P_max`, `A`, `range_max` and `range_min`, my above suggested parameterization of the `SoftBoundsDevice` would become 
 1. set as a shorthand for below `B = (range_max - range_min)/(1- exp(-P_max/A))` 
 2. `w_min := range_min`
 3. `w_max := B + range_min`
 4. `dw_min:= B/A`
 5. `up_down:= 1 + 2*range_min/B`

That is essentially the same what I suggested above but now defined with the new parameters. That seems to be what you suggest, right?

**Comment by wonjaeji** [comment]
@maljoras ,thank you for organizing again. However, I'm confused with the `up_down` parameterization.
According to the docs, I find `up_down` is defined as follows:
`dw = dwmin * (1 + up_down)` or `dw = -dwmin * (1 - up_down)`

Assuming that `range_max = - range_min` (did you also assume this condition?), `up_down` might be `range_min/B`:

1. `offset_up = dwmin*(1 + up_down) = (B/A)*(1 + range_min/B) = (B + range_min)/A`
2. `offset_down = dwmin*(1 - up_down) = (B/A)*(1 - range_min/B) = (B - range_min)/A`

So, I think that if you make a new data class over `SoftBoundsDevice`, then the condition should always be satisfied. Overall, this parameterization would design the same device what we suggested.

**Comment by maljoras** [comment]
If you calculate from the `dw_up = dwmin * (1 + up_down)` or `dw_down = -dwmin * (1 - up_down)` you'll find with `dw_min=dw_up - dw_down` that `up_down = (dw_up + dw_down) / (dw_up - dw_down)`.
 
Thus if you set  `dw_up = (w_min + B)/A` and `dw_down=(w_max - B)/A` (see above) you'll find that `up_down = (w_max + w_min)/ (w_max - w_min) = 1 + 2*range_min/B` and since `w_max = range_min + B` and `w_min=range_min`.

**Comment by wonjaeji** [comment]
@maljoras , the parameterization below you suggested is accurate, thanks a lot for the explanation. So, it would be very helpful to make a suggested device class.  The new device class would have variations on the slope and offset as `SoftBoundsDevice`.
> I see. In that case, if the user provides `P_max`, `A`, `range_max` and `range_min`, my above suggested parameterization of the `SoftBoundsDevice` would become
> 
> 1. set as a shorthand for below `B = (range_max - range_min)/(1- exp(-P_max/A))`
> 2. `w_min := range_min`
> 3. `w_max := B + range_min`
> 4. `dw_min:= B/A`
> 5. `up_down:= 1 + 2*range_min/B`
> 
> That is essentially the same what I suggested above but now defined with the new parameters. That seems to be what you suggest, right?

**Comment by maljoras** [comment]
Hi @wonjaeji ,
I have now added a new device model parameterization that does the transformaion as we discussed. See [documentation](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=SoftBoundsPmaxDevice#aihwkit.simulator.configs.devices.SoftBoundsPmaxDevice). One can just use it as the other devices, like:
```python
from aihwkit.simulator.configs.devices import SoftBoundsPmaxDevice
from aihwkit.simulator.configs import SingleRPUConfig

rpu_config = SingleRPUConfig(device=SoftBoundsPmaxDevice(alpha=0.02, range_min=-1, range_max=1, p_max=1000)) 

```
