### ISSUE TITLE
PCM presets

### ISSUE THREAD

**Issue by SaBaKa2020** [IBM/aihwkit#220]
Which of the available presets represent PCM devices?
If none, I was wondering if there is any plan to add PCM presets to the list of currently supported presets?

**Comment by maljoras** [comment]
Hi @SaBaKa2020,
many thanks for the request! Indeed, PCM is not among the presets currently, but in fact I am currently working on it and will add it very soon.

**Comment by SaBaKa2020** [comment]
Thanks @maljoras. Great news!
