### ISSUE TITLE
Analog tile with torch tensor interface

### ISSUE THREAD

**Issue by diego-plan9** [IBM/aihwkit#221]
## Description and motivation

Currently, each analog layer creates and maintain its own analog tile, invoking its functionality at selected points in time. An interesting alternative would be to move the analog tiles "closer" to being tensor-like entities, as it is likely to make the integration with torch easier and more robust and open more possibilities and use cases.

In particular:
* avoid workarounds for passing information such as in #211, #140 and others, and streamline other pieces.
* be able to treat them as first-class citizen in torch (either as `Parameters` or `Buffers` if needed)
* potentially being able to move functionality into them (optimizers, etc)
* simplify the library, potentially cutting down the number of code layers involved in some operations

## Proposed solution

Explore the possibility of creating a `AnalogTensor` which overloads the tensor functions that are implemented in analog (rank update, addr and matrix-matrix product mm):
https://pytorch.org/docs/stable/notes/extending.html#extending-torch-with-a-tensor-like-type

## Alternatives and other information

N/A

**Comment by SaBaKa2020** [comment]
Is it possible to define multiple tiles per kernel? Let say the device is a binary device (low and high resistance), and you want to have multiple cells per weight to achieve high precision weight representation. Then you will need multiple tiles per kernel where each tile represents a single bit position for all the weights in the kernel. 
Also, would it be possible to define multiple tiles per layer (corresponding to the number of kernels in the layer)?

**Comment by maljoras** [comment]
Hi @SaBaKa2020 ,
thank you for your question (best to open up a new issue for any new question, to make it easier to find). We have the option to have multiple unit devices per weight element (see `VectorUnitCell` [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=VectorUnitCell#aihwkit.simulator.configs.devices.VectorUnitCell)), however, the input is identical for each of the devices.   

If you want to have a specific layer, with scaled input you could build your own compound linear/conv layer by connecting multiple AnalogLinear/Conv layers each for a different scaled input slice and summing the output. Note that in this case the summing would happen after the ADC (in contrast to above, where the current is summed in analog).
