### ISSUE TITLE
Question on the ExpStepDevice

### ISSUE THREAD

**Issue by wonjaeji** [IBM/aihwkit#232]
## Description and motivation
Hello, I have a question on the `ExpStepDevice`. By running aihwkit, I got the response curve of the `ExpStepDevice` as below.

![image](https://user-images.githubusercontent.com/80827990/117987565-8e026800-b375-11eb-8391-8bae54391c36.png)

I tried to find out why `ExpStepDevice` responded like this by looking up to the documentation, and I wonder from what background this model is proposed. Is there any more documentation about the model? It will be of great help to me. Thanks a lot!

**Comment by maljoras** [comment]
Hi @wonjaeji,
thanks for the question!  The exp step model is described [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?aihwkit.simulator.configs.devices.ExpStepDevice#aihwkit.simulator.configs.devices.ExpStepDevice) (as you probably found already) and models an exponential dependence of the update step size with conductance.  The model is e.g. used for fitting PCM devices, e.g. in [Nadakumar et al. (2018)]( https://aip.scitation.org/doi/full/10.1063/1.5042408).  We also used it for fitting ReRam devices, which we include in the preset library (`ReRamESPresetDevice`, see [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.presets.devices.html#aihwkit.simulator.presets.devices.ReRamESPresetDevice) ) 

Note, that we now also have the `PowStepDevice` which might be useful for model fit (see [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=PowStepDevice#aihwkit.simulator.configs.devices.PowStepDevice) or the discussion on that #181 ).
