### ISSUE TITLE
Make use of the real device data instead of devices presets.

### ISSUE THREAD

**Issue by GihoLee97** [IBM/aihwkit#237]
First of all, I really enjoy exploring your works.
Thank you for your brilliant idea and this nice simulation tool.

While using this library, I come up with a question.
It seems that main approach of this library is using device model fitted as much as possible.
But I went to make use of the exact real data, especially conductance increment vs. conductance.

Is there any ways to simulate with exactly real devices characteristics that i missed? 
(Such as, update rule given by conductance increment vs. # of pulses data.)
If not, is there a plan to support this function?

Thank you!

**Comment by goldenhazard** [comment]
He is Korean!

**Comment by maljoras** [comment]
Hi @GihoLee97 ,
many thanks for your question!

One of the main goals of the simulator is to understand the effects of different hardware or material properties on the accuracy of the DNN training and for that it is important to have a parameterized curve that can by varied to explore impacts of hypothetical material properties and to test and improve algorithms for training and inference.

Another advantage of functional models for the device response curve is that it is straightforward to generalize to many devices and model device-to-device variations easily. If one wanted to model exactly an existing hardware, then one would have to provide (repeatedly measured) response curves for each individual device, which is not feasible in most cases.  

That being said, it might be still useful if one could provide arbitrary average response curves shapes together with some idea about the expected device-to-device variability and cycle-to-cycle noise. To not compromise too much on simulation speed, one could implement this with a look-up-table (or piecewise linear approximation) of a user-defined response curve (or more likely the relation of dG versus G). This is indeed something we have been thinking about a while ago and might provide in future.

**Comment by GihoLee97** [comment]
Thank you for your kind reply.
Your explanation makes me more understand the benefits of modeling.
Meanwhile, I might try to add those functionality within this library in few month.
If it goes well, i will let you know. (If you don’t mind. :) )
