### ISSUE TITLE
Report error when load model and use InferenceTitle

### ISSUE THREAD

**Issue by darrenkao** [IBM/aihwkit#260]
Hi, It still has some problems when I use inferencetitle.
1. I train model with a RPU Preset Config and save model.
2. I use `load_state_dict` to load my model when Inference
3. In inference, I use Inferencetile example in doc
![image](https://user-images.githubusercontent.com/33507350/122731731-2a415800-d2ae-11eb-963d-96f7ecd09b0f.png)
4. But when inferencing, it pops up errors like below:
![image](https://user-images.githubusercontent.com/33507350/122732129-8c01c200-d2ae-11eb-872c-3bd6daead1ce.png)

**Comment by maljoras** [comment]
Hi @darrenkao:
many thanks for raising an issue!  This error your are seeing is a result of a loading an state dict from a different RPU model. This is not supported in our simulator. In some exceptional cases, it might get expected results (for instance loading a floating point model with an `PulsedDevice`), but in most cases it makes no sense. We might add an explicit error message for this in future. 

The `InferenceTile` is the only tile we currently have that should be used for modeling hardware that is intended only for inference purposes and do not have any training capabilities (ie no hardware implementation of an update or backward pass).      
In the case of hardware only targeting inference, this `InferenceTile` is used to 1. perform hardware-ware training (using perfect update and backward pass in software) to optimize a DNN for running inferernce on the hardware, and 2. for testing the inference performance of the hardware with a programming noise model and an statistical noise model for investigating drift and retention. 

Thus the error you error you got is a result from not using the `InferenceTile` correctly. It cannot load a state dict that is derived from an `RPUConfig` preset. These presets are modelling analog hardware that is also capable of training in analog. So the hardware is really very different for `InferenceTile` versus presets, and we do not support to load a state dict from one to the other.

**Comment by darrenkao** [comment]
Very thanks for your nice reply and describe!

**Comment by maljoras** [comment]
Hi @darrenkao,
**to 1:** Yes, that is indeed possible.  All what you have to do is set the the forward pass to perfect:
```python
rpu_config = InferenceRPUConfig()
rpu_config.forward.is_perfect = True
```
You also want to avoid weight clipping (`clip`) or added noise training (`modifier`) in this case, if you really want to use the floating point case only.

**to 2:** We currently only have  a single PCM pair for inference.  We might support multiple pairs in future. One way to add this features would be to implement a new `MultiplePairConductanceConverter` analogous to the single pair converter (see [here](https://github.com/IBM/aihwkit/blob/master/src/aihwkit/simulator/noise_models.py#L63)). That would model the case where analog devices are added in analog (by adding their current) before the ADC.  For digital addition of bit slices, one could make a custom Module, that uses one `InferenceTile` for each weight slice and then add the output.

**Comment by darrenkao** [comment]
Hi @maljoras ,
Thanks for your kindly reply again,
After I studied the document, I have some questions
From my understanding, the behavior of `InferenceTile` with PCM Noise Model is 
1. flexible PCM Array size (It means assuming array size is the same as size of input tensor and output tensor), 
> It seems column and row size of each layer is always the same as input  and output kernel size. Despite I try to set parameter `in_size` and `out_size` to `InferenceTile` as a fix number, it will be modified by program automatically.

2. According to item 1, noise only inject to a weight matrix once due to tile size is infinite (A weight matrix will not divide to several tile to process),
3. Assume parameter of `inp_res` is set to 1/256, the input will serial compute 1 bit by 1 bit for 8 cycle and inject 8 different noise due to cycle-by-cycle variation
Are above correct?

Many thanks for your help again!

**Comment by maljoras** [comment]
Hi @darrenkao ,
Indeed, the tile size currently adapts to the layer at hand. We do not have any automatic mapping scheme. However, if needed you could add a custom mapping quite easily, by writing a new module which has 2 or more `AnalogTiles` and inputs are distributed to those tiles as appropriate in the forward method. For instance: 

```python
class MyModule(nn.Module):
def __init__(self,...):
    self.linear1 = AnalogLinear(...)
    self.linear2 = AnalogLinear(...)

def forward(self, x ):
    x_part1, x_part2 = split(x)   # add some logic here
    y1 = self.linear1(x_part1)
    y2 = self.linear2(x_part2)
    return combine(y1, y2)  # add some logic here
```
Where one needs to add some logic for the split and combine function as appropriate. 

In this case noise is added for each tile separately of course.

Regarding 3: The DAC is just a linear quantization modelling a pulse width modulation input, where the input is quantiized and only one mat-vec pass is computed. We do not yet support bit sliced input schemes (however notice that the iterative [bound management](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.utils.html?highlight=bound_management#aihwkit.simulator.configs.utils.BoundManagementType) recomputes the result with scaled inputs if the output was clipped). 

Nevertheless, you could again write a simple module like the above to achieve it:

 ```python
class MyBitSliceModule(nn.Module):
def __init__(self,...):
    self.linear = AnalogLinear(...)

def forward(self, x ):
    x_slices =  make_bit_slices_from_x(x)  # add some logic here
    y_slices = []
    for bit_slice in x_slices:   
         y_slices.append(self.linear(bit_slice))
    return combine_slices(y_slices)  # add some logic here
``` 

If you decide to write your own module, consider contributing them to the code base! That would be highly appreciated.

**Comment by darrenkao** [comment]
@maljoras 
Thank you very much for your kindly help again!
I will try to build these, also to ask for advice here when I face problems...
If it works well, it's my honor to contribute

**Comment by darrenkao** [comment]
@maljoras 
Following about the first problem in this thread, there are new problem.
I use InferenceRPUConfig to train my model and save. After that, I also use InferenceRPUConfig and try to load this model back to do inference, but the class mismatch error pops up like below:
![image](https://user-images.githubusercontent.com/33507350/124581921-1f78ec80-de84-11eb-8ac0-6eaf9aa3a16c.png)

**Comment by kaoutar55** [comment]
Hi @darrenkao 
Can you share a snippet of the code you used to hw-aware train the model. It seems that the training still uses AnalogTile.

**Comment by darrenkao** [comment]
Hi @kaoutar55 ,
I have solved the problem. The problem is caused by I didn't give some analog layer parameter `rpu_config`, so the program default use AnalogTile not InferenceTile. I think it better to warn user about empty rpu_config than using default rpu config due to it's hard to think about this problem directly if I get tile class mismatch error when debuging.

**Comment by kaoutar55** [comment]
Good point. @darrenkao we will add this warning. Thanks for pointing this out!
