### ISSUE TITLE
Error when import compiled aihwkit lib

### ISSUE THREAD

**Issue by darrenkao** [IBM/aihwkit#272]
## Description
I compiled and run AIHWKIT successfully  on a server with cuda 11.0, nvcc 11.1, gpu=2080ti

Now, I try to compile AIHWKIT on a server with cuda 10.2, nvcc 10.2, gpu=Tesla v100

In compile stage, it success and generate lib '.so'

but when I use this lib to run example, it pop up error like below
![image](https://user-images.githubusercontent.com/33507350/123508652-41fc5000-d6a3-11eb-92d5-a1a48c4f497d.png)

* Pytorch version: 1.4
* OS: Nvidia DGX
* Python version:3.6.9
* Conda version (or N/A): 4.7.12

**Comment by diego-plan9** [comment]
> Pytorch version: 1.4

Can you confirm this is accurate? We only officially support `PyTorch>=1.7` - if this was not a typo, could you try with a more recent torch version (1.7 or 1.8)? 

Also, can you verify explicitly that you are running the compilation in a "clean" state? The easiest way to achieve it by running `make clean` prior to compiling via `make build_inplace` - the first command will ensure that there are no leftovers from previous compilations which might be interferring.

**Comment by darrenkao** [comment]
Hi @diego-plan9 ,
Unfortunately, this problem still happens after I update pytorch to above 1.7. but I solved finally.
The problem is occur on pytorch conda version, it seems include CPU and GPU version in one package. So linking lib of compile and execute mismatch...
My solving method is installing a local pure gpu pytorch and torchvision and force set parameter `TORCH_INCLUDE_DIRS` and `TORCH_LIB_DIR` in `cmake/Modules/FindTorch.cmake` to my local torch directory. (Due to in `FindTorch` file, it gets path according to system python environment which has pytorch conda version)

**Comment by maljoras** [comment]
@darrenkao thank you! I am closing this issue as it seems solved.
