### ISSUE TITLE
How to access the source code?

### ISSUE THREAD

**Issue by kannanum** [IBM/aihwkit#304]
Hi,
          Thanks to the IBM developers for this great package. Can you please help me to access the source code of the package? I could not find the original source code from the docs page.

**Comment by maljoras** [comment]
Hi @kannanum,
many thanks for your interest! All the source code is available from this github page. You can just clone the project from this page to get the source code locally onto your computer (just select the "code" tab [here](https://github.com/IBM/aihwkit)). Or you could just download the [zip file of the current master branch](https://github.com/IBM/aihwkit/archive/refs/heads/master.zip).

**Comment by kannanum** [comment]
Thanks @maljoras ,
          Thanks for letting me know. I could find the source files from the aihwkit/src/aihwkit folder from the master branch.
Just a suggestion. It would be very helpful for the user to access the source code from the 'docs' page corresponding to each of the module. something like this would be much helpful
![Capture2](https://user-images.githubusercontent.com/31684180/140855696-2a5410ee-f6bd-4ddc-9038-83f47a5ec36b.PNG)
es
Regards,
Kannan

**Comment by kaoutar55** [comment]
That's a good suggestion @kannanum! Thank you! We will add that in our next revision of the documentation.

**Comment by maljoras** [comment]
Hi @kannanum:
indeed good suggestion. That should actually be easy to change, as it is just a sphinx package. Should be enabled with #305 .
