### ISSUE TITLE
Questions regarding noise model

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#324]
Hello,

In your documentation, in the section "" you explained about read noise, and presented it's spectral density. could you please explain to me who are G and Q in this equation?

![image](https://user-images.githubusercontent.com/48283282/142139794-5bf863e7-48f5-43c8-996e-2f8d3ffa75ed.png)

2. I have another small question, you use `log` function in some places, is it in 10 base or 2?

3. could you please explain what is t_c? could you give a numeric example? t_c needs to be relative to something isnt it? we thought it is the delta between the encoding of the PCM and the sampling of the conductance g(t_c)

![image](https://user-images.githubusercontent.com/48283282/142173354-6caef8d3-efaa-468e-acbc-3d6d38b445a2.png)

Thank you!

**Comment by anu-pub** [comment]
1. G is the conductance and Q is a factor that represents the magnitude of the noise. Note that Q=Q_s^2. 

2. Log is base e, so ln. 

3. t_c is indeed the elapsed time between programming the PCM and the sampling of conductance. It denotes the elapsed time between the last programming pulse and when the conductance is read afterwards. So say if 1s is elapsed between the last pulse sent and the reading conductance value g_prog, we have t_c = 1s. So t_c is always relative to the last programming pulse that was sent to the device.

**Comment by ElinorG11** [comment]
Thank you very much for your detailed answer. There's one small thing I'd like to make sure about point [1]: is G the target conductance (i.e., g_T)? or the noisy conductance actually measured (i.e., g_read)?

**Comment by anu-pub** [comment]
G would be the actual device conductance free of read noise, that is, g_drift(t).

**Comment by ElinorG11** [comment]
I see, thank you very much!
