### ISSUE TITLE
determining the shape of a Tile by layer size

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#330]
Hello,

In another issue, you explained to me that the Tile size is determined by the layers sizes. i.e., it will be big enough to contain all the parameters for each layer in a single crossbar (no bit slicing). Could you please explain how exactly the calculation is done? if for example I have a model with 1 layer, this is the information of the layer retrieved by summary() function:

```
----------------------------------------------------------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1         [-1, 64, 224, 224]           1,792
```

how can I know what will be the dimensions of the tile that will be created? (I'm using a torch model and I apply on it `convert_to_analog()`)

Thank you.

**Comment by maljoras** [comment]
Please take a look at standard conv2d function from pytorch explaining large the weight is (see [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html) ). 

By the way, we have a new PR that will soon be merged that calculated the tile size that might be interesting (see #316).  Also note that we have now a new `AnalogLinearMapped` layer that limits the tile size to a certain size (#320). A mapped conv version will follow soon (next week)

**Comment by ElinorG11** [comment]
Thank you very much for your answer! just to make sure I understand correctly - basically now you support bit-slicing, and all the tiles will be the same size? Thank you once again.

**Comment by maljoras** [comment]
I am not entirely sure what you mean by "bit slicing". What is implemented with the "mapped" layers is mapping a larger weight matrix onto multiple smaller crossbar arrays (aka analog tiles).  Bit slicing, that is slicing only parts of the input vector can be easily incorporated by building your own analog module which is based on the existing analog modules. You just have to change the input as desired, and apply it to the analog module and add the outputs.
