### ISSUE TITLE
Get the output of each layer of the analog model

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#332]
Hello,

I have trained models (with their trained weights) and I want to convert them to analog using the `convert_to_analog()` function you supply. I'm trying to print the output of each analog layer separately, but I'm not sure exactly where you pass the data to the `forward()` function of each layer. 

I have installed on my computer an old version of the kit, number 0.4.0 about a month ago (before the `convert_to_analog_mapped`) and I tried to change the forward function in `nn/modules/conv` such that it will print the return value of `AnalogIndexedFunction.apply()` method instead of just returning it in the following manner:
```
def forward(self, x_input: Tensor) -> Tensor:
        """Compute the forward pass."""
        input_size = x_input.numel() / x_input.size(0)
        if not self.fold_indices.numel() or self.input_size != input_size:
            self.recalculate_indexes(x_input)

        out = AnalogIndexedFunction.apply(
            self.analog_tile.get_analog_ctx(), x_input,
            self.analog_tile.shared_weights, not self.training)

        print(out)

        return out
```

I also looked at your new version of the kit, where the forward function located in `src/aihwkit/nn/linear_mapped.py` in this [link](https://github.com/IBM/aihwkit/blob/eb887425be24aad45faf44ad093685e9f828c86d/src/aihwkit/nn/modules/linear_mapped.py#L258) and I saw that in line 263 you calculate the output of the `AnalogLinear` layer, I thought I can clone the new kit and just print the `out` variable to get the output, but when I tried to do this I got an error saying that there's no module named `aihwkit.simulator.rpu_base` since I didn't really install the kit using the developer installation from scratch but just cloned it, I thought that if I already configured it once I don't need to go through all the installation once again and it is sufficient to just update the cloned repo... 

Perhaps you have any advice on what should I do? Can I use the old version (0.4.0 with the function `convert_to_analog()`) and apply small changes to it such that it will print the output of each analog layer?

Thank you.

**Comment by maljoras** [comment]
Hi @ElinorG11:
I would strongly advise you against "hacking" the AIHWKIT's code in the way you are suggesting. It will use all compatibility with any updates and is in general not a good idea. You should not modify the AIHWKIT source code unless you want to contribute something or know exactly would your are doing.  You would also not change the code of torch, for example, but instead would use its functionality to reach your desired goal.

One way to get the output of a given layer is using "hooks" in pytorch. This would be the way to go. You can read more about it in this (external) [blog](https://medium.com/the-owl/using-forward-hooks-to-extract-intermediate-layer-outputs-from-a-pre-trained-model-in-pytorch-1ec17af78712), or on the documentation pages of torch.

**Comment by ElinorG11** [comment]
Thank you, I've had some problems using "hooks" (something with state dictionary), but I'll trying looking into it some more
