### ISSUE TITLE
Using program_analog_weights function 

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#339]
Hello,

I'm trying to mimic the example you've added [here ](https://aihwkit.readthedocs.io/en/v0.4.0/pcm_inference.html#example-of-how-to-use-the-pcm-noise-model-for-inference) that explains how to use the pcm noise model for inference, but I'm having trouble importing `program_analog_weights` and `drift_analog_weights` from the `AnalogModuleBase` class in `aihwkit.nn.modules.base`. I'm trying to use it this way:

````
    # Convert the model to its analog version.
    net = convert_to_analog(model_to_convert, rpu_config, weight_scaling_omega=0.6)
    
    net.eval()
    
    t_inference = 3600. # time of inference in seconds (after programming)
    
    program_analog_weights(net) # can also omitted as it is called below in any case
    drift_analog_weights(net, t_inference) # modifies weights according to noise model
````

but I get an error saying the functions `program_analog_weights` and `drift_analog_weights` are not defined, although in your example you didn't use any imports.

Thank you

**Comment by maljoras** [comment]
Hi @ElinorG11 ,
When converting models, that are not  of type `Sequential` in the root module, the converted model is not of AnlagoSequential and thus does not have the methods. A simple solution is to make the converted net an `AnalogSequential`:
```python
net = AnalogSequential(net)
```
after the conversion and before calling `program_analog_weights` etc.

**Comment by ElinorG11** [comment]
Thank you very much for your answer. There's one thing I don't quite understand: when I'm using `convert_to_analog|()`, are the noises added and activated automatically (if I defined them in the rpu) as follows:

```
from aihwkit.simulator.configs import InferenceRPUConfig
from aihwkit.simulator.configs.utils import WeightNoiseType
from aihwkit.inference import PCMLikeNoiseModel, GlobalDriftCompensation

# Define a single-layer network, using inference/hardware-aware training tile
rpu_config = InferenceRPUConfig()

# specify the noise model to be used for inference only
rpu_config.noise_model = PCMLikeNoiseModel(g_max=25.0) # the model described

# specify the drift compensation
rpu_config.drift_compensation = GlobalDriftCompensation()

# build the model (here just one simple linear layer)
model = convert_to_analog(pytorch_model)
```

or do I have to use this code section as well to see their influence:

```
model.eval()        # model needs to be in inference mode
t_inference = 3600. # time of inference in seconds (after programming)

program_analog_weights(model) # can also omitted as it is called below in any case
drift_analog_weights(model, t_inference) # modifies weights according to noise model

# now the model can be evaluated with programmed/drifted/compensated weights
```

I'm asking since in examples #17+18 you perform conversion to an existing model and evaluate it w.o using the second code snippet I added, but on the other hand, as explained here: https://aihwkit.readthedocs.io/en/latest/pcm_inference.html#example-of-how-to-use-the-pcm-noise-model-for-inference
the noises are added only by using this snippet...


Thank you

**Comment by maljoras** [comment]
There are two types of "noises" (or non-idealities). The first are inherent to the analog matrix-vector product. These are set by the `forward` field and always applied for each mat-vec. The second type are the more long-term effects onto the weights for inference, which are governed by the `noise_model`. These are applied statically to the weights only when you call `program_analog_weights` (programming noise added to weights) and `drift_analog_weights` (long term weight drift and accumulated noise depending on time of inference `t_inference`).

**Comment by ElinorG11** [comment]
I see, thank you very much!
