### ISSUE TITLE
Using compensation method to mitigate the effect of drift

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#340]
Hello,

I'm trying to use the compensation method to mitigate the effect of drift. I saw it is implemented in `aihwkit/src/aihwkit/inference/compensation/drift.py` using the functions `readout` and `get_readout_tensor` and I have two questions about proper usage:

1. From what I understood, it is not applied automatically, and I need to activate them in the following way:
```
    # drift compensation
    rpu_config.drift_compensation = GlobalDriftCompensation()

    rpu_config.drift_compensation.get_readout_tensor(?)
```
I wasn't sure when to use `readout` (and whether I need it at all) and what integer to pass as input to `get_readout_tensor`. Could you please correct me if I'm using it in a wrong way?

2. What is the meaning of the `in_size` parameter that the function `get_readout_tensor` gets?

Thank you for your help!

**Comment by maljoras** [comment]
Drift compensation is turned on by when defined in the `rpu_config` as you did in your example. You don't need to do anything beyond that, the readout is called automatically and the drift compensation is applied when calling `drift_analog_weights`.

The the `get_readout_tensor` can be used (overridden) to implement your own drift compensation class.

**Comment by ElinorG11** [comment]
Thank you for the clarification
