### ISSUE TITLE
get weights of AnalogSequential layer

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#341]
Hello,

I'm trying to get the weights of an `AnalogSequential` layer, but I can't figure out how to do it. Is it possible to get it's weights? I'm asking because as you advised me here: https://github.com/IBM/aihwkit/issues/339 in order to add the noises I need to convert the net to `AnalogSequential`, but when I want to get it's weights I get an error saying `AnalogSequential`doesn't have a method `get_weights`

Thank you

**Comment by maljoras** [comment]
Hi:
only analog modules have the `get_weights` functionality as Sequential is just a list of modules. You can just index the sequential to get the module:
```python
model = AnalogSequential(...)
model[0].get_weights()
```
and so on.

**Comment by ElinorG11** [comment]
it worked. Thank you very much!
