### ISSUE TITLE
Buffer size mismatch. This should never happen! error

### ISSUE THREAD

**Issue by Anchick** [IBM/aihwkit#342]
## Description

Hello, I am having the following error:

File "/home/USERNAME/.conda/envs/aihwkit_cuda/lib/python3.8/site-packages/aihwkit-0.4.0-py3.8-linux-x86_64.egg/aihwkit/simulator/tiles/base.py", line 541, in backward return self.tile.backward(d_input, self.bias, self.out_trans, self.in_trans)
RuntimeError: Error in rpucuda.cu:331  Buffer size mismatch. This should never happen!

This error occurs if batch size used is large enough. 
## How to reproduce
03_mnist_training.py example uses default batch size of 64, but in my case it pops mentioned error, before training loop starts. With batch size of 32 there is no errors and training loop goes as expected. 

Same error of buffer size mismatch occurs in other examples, but no errors if batch size used is low enough. Example 11_vgg8_training gives no error with batch size of 8.

## Expected behavior

Training proceeds without any buffer mismatch errors. 

## Other information

aihwkit was compiled with CUDA support for 7.5 architecture [python setup.py install -DUSE_CUDA=ON -DRPU_CUDA_ARCHITECTURES="75"].
nvidia-smi command shows just 2-3 GBs of GPU RAM usage, out of 46 GBs available. 

* Pytorch version: 1.8.1
* Package version: 0.4.0
* OS: CentOS 7
* Python version: 3.8
* Conda version (or N/A): 4.10.3

**Comment by maljoras** [comment]
Hi @Anchick,
many thanks for the bug report! Indeed, we also noticed this error which occurred when the batch size is dynamically changed in version 0.4. This error should be resolved already in the current version cloned from git (see #294). The fix will be included in the soon upcoming version 0.5.
