### ISSUE TITLE
Question about using ordinary (digital) optimizers on analog layers

### ISSUE THREAD

**Issue by Winfriedvdd** [IBM/aihwkit#355]
Hi!
It seems my models also train when using Adam or SGD, instead of the AnalogSGD provided in the package. Am I safe to assume that the analog trainers are meant for on-device training, whereas hardware-aware training can (and should) be optimally performed using regular trainers?

Or are there any important differences that I should be aware of when aiming for optimal hardware-aware training?

Thanks in advance!

**Comment by maljoras** [comment]
Hi @Winfriedvdd:

that is correct, the hardware-aware training can be done with any optimizer from pytorch (or with AnalogSGD which then defaults to standard SGD). The analog-aware optimizers are only necessary for analog training.
