### ISSUE TITLE
How are the tests supposed to be run?

### ISSUE THREAD

**Issue by ZhenmingYu** [IBM/aihwkit#371]
## Description and motivation

There are currently no main() functions for the tests, which makes it difficult for beginners.
Unlike the examples where everything is just straightforward.

## Proposed solution

Document the tests and how are they supposed to be used.

## Alternatives and other information

Make a main.py file for the tests folder.

**Comment by maljoras** [comment]
Hi @ZhenmingYu :
we use pytest for unit tests, which does not need any ``main.py`` file. We use a number of common developmental tools which can be installed with ```pip install -r requirements-dev.txt```

To run the full test suite simply do (from the command line):
```make pytest```

To run individual test files, you can use, e.g.  
```pytest -v -s tests/test_presets.py```

Individual tests can be run by giving the name, e.g.:
```pytest -v -s tests/test_presets.py::PresetTest_TTv2IdealizedPreset::test_tile_preset ```

You can also look up the documentation of [pytest](https://docs.pytest.org/en/7.1.x/)

**Comment by maljoras** [comment]
Reopening the issue, because we should indeed add this to the  documentation @kaoutar55

**Comment by kaoutar55** [comment]
@maljoras  agree. I will add a section about examples in the public documentation.
