### ISSUE TITLE
Is it possible to add secondary(hidden) weights?

### ISSUE THREAD

**Issue by ZhenmingYu** [IBM/aihwkit#379]
## Description and motivation

I am trying to develop a new device model for aihwikit. And I would like to store secondary(hidden) weights alongside the real weights.

For example, the hidden weights could be the oxygen vacancy concentration in oxide-based memristors.
Which determines the device conductance, and in return, determines the represented weights in PyTorch layers.

 Is it possible to store these hidden weights somewhere other than the "T **weights" but can still be passed into the update functions?

Thanks

-----------------------------------------------------
update:

Are the w_slope_up_ and w_slope_down_ in rpu_linearstep_device.h what I want?
I see that it is an array of size (d_sz, x_sz) and gets passed into the update functions.
However, I am having a bit trouble understanding the different parts of "BUILD_PULSED_DEVICE_CONSTRUCTORS"

**Comment by maljoras** [comment]
Hi @ZhenmingYu:
Correct, we have a number of devices that actually use hidden weights. For instance, the LinearStepDevice has a hidden weight that is updated and an "visible" weight that can be a noisy version of the former (implementing write noise). Also the `TransferCompounds` are complex devices with many hidden weights. They are accessible with `tile.get_hidden_parameters` in python. The only constraint is that the C++ RPU device needs to govern the apparent weights that have to written (and fixed) after each update, ie these are the weights that are used by the forward and backward pass. 

The `BUILD_PULSED_DEVICE_CONSTRUCTOR` (defined [here](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_pulsed_device.h#L267)) is just a helper macro that implementd all necessary functions for a new `PulsedRPUDevice` class. If you do not use it, you need to make sure that you override all necessary methods. 

In the standard `PulsedRPUDevice` there is actually the support of one additional hidden device matrix already built in (which is typically used for the write noise, but you might not need that). If you use that additional matrix, you can reuse many of the functions present even for GPU. Of course, you can always write a more complicated device (e.g. [VectorRPUDevice](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_vector_device.h#L129) can have n hidden devices), but then you need to implement more of the required methods in the device class.     

To re-purpose the write noise functionality as a hidden weight, you can essentially use the `w_apparent` as your apparent weight (that is seen by the forward and backward function) and use w as your hidden weight (see [here](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_linearstep_device.cpp#L121)). However, you need to make sure that the [w_apparent is enabled](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_linearstep_device.cpp#L121)  and might want to rename the hidden parameter fields (by overriding the [base implementation](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_pulsed_device.cpp#L249)).

**Comment by ZhenmingYu** [comment]
Dear @maljoras 

Thanks a lot for the reply. I'm getting back at this project recently, and your advice was very helpful.

However, I have some additional questions regarding the matter.

To enable the "persistent weight" in `PulsedRPUDevice`, I need `implementsWriteNoise()` and `usesPersistentWeight()` to return `True`.
The first one can be easily overridden, and the second one requires `write_noise_std>0`.

I want to hide this from the end-user since I repurposed the "persistent weight" for other functionality, so I want to set `write_noise_std=1` in the C++ codes, rather than leaving a default in the python files.

Where should I do this actually? 
I tried typing `write_noise_std = 1;` in the `BUILD_PULSED_DEVICE_META_PARAMETER` and in the `populate` function.
Both ended with errors from the compiler.

I really appreciate any help you can provide.
