### ISSUE TITLE
Noise model fitted and characterized on RRAM devices (programming noise and output-referred read noise)

### ISSUE THREAD

**Issue by frmar440** [IBM/aihwkit#394]
## Description and motivation

Add a new noise model based on real RRAM devices. At the moment, only a PCM statistical model is available for analog inference. A RRAM preset exists for analog training, but there are no noise models for inference only (after digital training). Since RRAM devices are promising for in-memory computing, such a model would be interesting for simulation and hardware-aware training.

## Proposed solution

Extend the existing library to consider both programming and read noises of RRAM devices fitted on real hardware.

## Alternatives and other information

Our research group is fabricating and characterizing RRAM devices, so I'll work on adding this feature in the library.

**Comment by maljoras** [comment]
Hi @frmar440 ,
many thanks, that sounds like a great contribution!

**Comment by maljoras** [comment]
Hi @frmar440, any update on this issue?

**Comment by matifali** [comment]
Looking forward to it. Also can you point out some literature regarding this? May be I can contribute for ReRam model.

**Comment by maljoras** [comment]
We have added a (rudimentary) ReRAM inference model.  One can use is by setting
```python
from aihwkit.simulator.configs import InferenceRPUConfig
from aihwkit.inference import ReRamWan2022NoiseModel
rpu_config = InferenceRPUConfig(noise_model=ReRamWan2022NoiseModel())
```
Note that only some times are fitted to the published data (1 second, 1 day, 2 days)

**Comment by maljoras** [comment]
Closing this issue since we have added the above ReRAM model. Please re-open if a new model is required.
