### ISSUE TITLE
apply_programming_noise() only used if drift compensation is enabled for InferenceTile 

### ISSUE THREAD

**Issue by marcusvaltonen** [IBM/aihwkit#416]
## Description
In `aihwkit/simulator/tiles/inference.py:117` apply_programming_noise() is called and the programmed weight assigned to
self.programmed_weights; however, `set_weights()` is only called if drift compensation is used.

## How to reproduce

```
import torch
from aihwkit.nn import AnalogLinear
from aihwkit.simulator.configs import InferenceRPUConfig


rpu_config = InferenceRPUConfig()
rpu_config.drift_compensation = None  # <-- If this line is removed the weights are programmed
n = 3
A = torch.arange(0, n*n, dtype=torch.float32).reshape(n, n)
model = AnalogLinear(n, n, bias=False, rpu_config=rpu_config)
model.set_weights(A)
model.eval()
model.program_analog_weights()
prog_weights = model.get_weights()[0]
print(prog_weights)

```

## Expected behavior
I find it counter-intuitive that the weights are only applied if drift compensation is enabled,
as they are two different phenomena. I would like to change

```
self.programmed_weights, self.nu_drift_list = self.noise_model.apply_programming_noise(
    self.reference_combined_weights)

if self.drift_compensation is not None:
    self.tile.set_weights(self.programmed_weights.numpy())
    forward_output = self._forward_drift_readout_tensor()

    self.drift_baseline = self.drift_compensation.init_baseline(forward_output)
```
to

```
self.programmed_weights, self.nu_drift_list = self.noise_model.apply_programming_noise(
    self.reference_combined_weights)
self.tile.set_weights(self.programmed_weights.numpy())

if self.drift_compensation is not None:
    forward_output = self._forward_drift_readout_tensor()

    self.drift_baseline = self.drift_compensation.init_baseline(forward_output)
```

**Comment by maljoras** [comment]
Hi @marcusvaltonen,
Many thanks for the bug report! 
This was indeed a bug, but I believe we have fixed this already with the [recent PR](https://github.com/IBM/aihwkit/pull/389). For the bugfix you have to install the new version from the master branch directly. I am assuming you used an earlier version and not the most recent one?

**Comment by marcusvaltonen** [comment]
Perfect, I was using the 0.5.1 branch. Much appreciated!
