### ISSUE TITLE
Verifying the Installation (Read the Docs)

### ISSUE THREAD

**Issue by joris-gentinetta** [IBM/aihwkit#443]
## Description
The code from read the docs (https://aihwkit.readthedocs.io/en/latest/install.html) to verify the pip installation of the package throws an error because the input dimension of the AnalogLinear layer does not correspond to the dimension of the input. 

from torch import Tensor
from aihwkit.nn import AnalogLinear

model = AnalogLinear(3, 2) #change 3 to 2
model(Tensor([[0.1, 0.2], [0.3, 0.4]])) #or add another feature to the inputs

**Comment by maljoras** [comment]
Hi @joris-gentinetta
good catch !
