### ISSUE TITLE
Missing zero_grad() call

### ISSUE THREAD

**Issue by PierreTsr** [IBM/aihwkit#446]
## Description

It seems like the first two examples (`examples/01_simple_layer.py` and `examples/02_multiple_layers.py`) are missing a call to `opt.zero_grad()` at each iteration. When running on 10 iterations currently the loss decrease then increase again:
```
Loss error: 1.0298337936401367
Loss error: 0.8178885579109192
Loss error: 0.4703792631626129
Loss error: 0.1962183117866516
Loss error: 0.0619336031377316
Loss error: 0.0884876772761345
Loss error: 0.2775749266147614
Loss error: 0.5320941805839539
Loss error: 0.7531698346138000
Loss error: 0.8695605397224426
```

## How to reproduce

Run `examples/01_simple_layer.py` or `examples/02_multiple_layers.py` (it is more noticeable on 10 iterations than 100).

## Expected behavior

The loss should decrease consistently, as when `opt.zero_grad()` is added:
```
Loss error: 1.1083202362060547
Loss error: 0.3732085227966309
Loss error: 0.1592179238796234
Loss error: 0.0920740887522697
Loss error: 0.0612552836537361
Loss error: 0.0359693244099617
Loss error: 0.0363772809505463
Loss error: 0.0245949663221836
Loss error: 0.0224329363554716
Loss error: 0.0218768958002329
```

## Other information

simply adding `opt.zero_grad()` after each `opt.step()` should be sufficient to solve this.

**Comment by maljoras** [comment]
Thanks @PierreTsr,
you are right, many thanks. I noticed that also, but forgot to change it. Will do.
