### ISSUE TITLE
Indice size Error in rpu_onesided_device

### ISSUE THREAD

**Issue by bus6479** [IBM/aihwkit#447]
## Description

IBM/aihwkit/tree/master/src/rpucuda/rpu_onesided_device.cpp
208 line initUpdateCycle()
a_indices_ ,b_indices_ are resized into too small size
## How to reproduce
If you simulate FCN which has many nodes like 784x256x128x10 with OneSidedUnitCell
Because we need x_size of a_indice and b_indice at max in sparse update

## Expected behavior
Segmentation Fault or Errors related to memory size occur occasionly

## Other information
 213-216 line have to be changed into
if (a_indices_.size() < (size_t)this->x_size_) {
    a_indices_.resize(this->x_size_);
    b_indices_.resize(this->x_size_);
  }

* Pytorch version:
* Package version:
* OS:
* Python version:
* Conda version (or N/A):

**Comment by maljoras** [comment]
Hi @bus6479 
Many thanks for noting this. Indeed, it is as you write.
