### ISSUE TITLE
AttributeError in a notebook example

### ISSUE THREAD

**Issue by saba-er** [IBM/aihwkit#451]
Hi @kaoutar55 
When running the notebook example analog_sensitivity_LeNet5.ipynb, I face this error in cell [19]:
AttributeError: 'FloatingPointRPUConfig' object has no attribute 'forward'. 
The error corresponds to this line: rpu_config.forward.inp_res = DAC.value.

For your reference, I have built the environment from the latest release of the source code. 
Some info about my simulation environment:
Ubuntu 20.04
Torch version: 1.13.0+cu117
Python version:  3.8.10

**Comment by maljoras** [comment]
Hi @saba-er,
many thanks for the issue. The floating point RPU config indeed has no DAC so it cannot be used to change the DAC resolution.
