### ISSUE TITLE
Unexpected device parameters when using ConstantStepDevice

### ISSUE THREAD

**Issue by jiwonjae** [IBM/aihwkit#457]
Hi all, hope you are well.

## Description

I want to create a `ConstantStepDevice` by specifying four parameters - `w_min,` `w_max,` `up_number_of_states (up_pulses),` and `down_number_of_states (down_pulses).` By doing so, I expect the device's weight would reach across `w_min` and `w_max` by giving the exact number of pulses - `up_pulses` and `down_pulses.`
I think the function `create_device` below should do the job, but it did not. Can you please review this issue? Thanks!

## How to reproduce

I believe the code below would reproduce the situation I'm describing.

```python
import numpy as np
import matplotlib.pyplot as plt

from aihwkit.simulator.configs import SingleRPUConfig
from aihwkit.simulator.tiles.analog import AnalogTile
from aihwkit.simulator.configs.utils import UpdateParameters
from aihwkit.simulator.configs.devices import ConstantStepDevice

from torch import ones
one = ones((1, 1))

def create_device(up_pulses, down_pulses, w_min, w_max):
    device = ConstantStepDevice()

    dw_up = (w_max - w_min)/up_pulses
    dw_down = (w_max - w_min)/down_pulses
    dw_min = (dw_up + dw_down)/2
    up_down = (dw_up - dw_down)/(dw_up + dw_down)

    print(f"From the definition, dw_up = (w_max - w_min)/up_pulses = {dw_up},")
    print(f"and dw_down = (w_max - w_min)/down_pulses = {dw_down}.")
    print(f"Then, dw_min should be set to {dw_min} and up_down should be set to {up_down}")
    print(f"so that dw_up = dw_min*(1+up_down) = {dw_min*(1+up_down)},")
    print(f"and dw_down = dw_min(1-up_down) = {dw_min*(1-up_down)}.")

    device.dw_min, device.dw_min_dtod, device.dw_min_std = dw_min, 0., 0.
    device.up_down, device.up_down_dtod = up_down, 0.
    device.w_max, device.w_max_dtod = w_max, 0.
    device.w_min, device.w_min_dtod = w_min, 0.

    return device


w_min, w_max = -1, 1
up_pulses, down_pulses  = 20, 10
initial_weights = w_min

test_rpu = SingleRPUConfig(
    device=create_device(up_pulses, down_pulses, w_min=w_min, w_max=w_max), 
    update=UpdateParameters(desired_bl=1)
    )
test_tile = AnalogTile(out_size=1, in_size=1, rpu_config=test_rpu)

test_tile.set_weights(weights=initial_weights*one, biases=None, realistic=False, n_loops=1)
test_tile.set_learning_rate(learning_rate=1.)

hidden_params = test_tile.get_hidden_parameters()
print(f"However, dw_up and dw_down is set to {hidden_params['dwmin_up']} and {hidden_params['dwmin_down']}")

weight_list = np.array(test_tile.get_weights(realistic=False)[0][0])

for _ in range(up_pulses):
    test_tile.update(x_input=one, d_input=-one)
    weight_list = np.concatenate((weight_list, np.array(test_tile.get_weights(realistic=False)[0][0])))

for _ in range(down_pulses):
    test_tile.update(x_input=one, d_input=one)
    weight_list = np.concatenate((weight_list, np.array(test_tile.get_weights(realistic=False)[0][0])))

plt.figure(figsize=(10,8))
plt.scatter(range(up_pulses+down_pulses+1), weight_list)
plt.grid()
plt.show()
```

I get the `test_device`'s weight trace as below (all realistic options are turned off).
![41ef49bb-b015-4c1d-9692-6d36555eb05e](https://user-images.githubusercontent.com/93390181/209195469-108cf95d-fd1c-4910-b99e-d7f77dc146ad.png)

## Expected behavior

I expect the weight trace below, which I obtained manually by setting `hidden_params.`
![4f59a2bb-eac9-4152-a10d-8e26461731fe](https://user-images.githubusercontent.com/93390181/209195778-e29e3213-a6b6-42f7-8246-2a3e4eed300d.png)

## Other information
* Package version: 0.6.0

**Comment by maljoras** [comment]
Hi @jiwonjae,
Many thanks! 

Looks like that you defined the `up_down` not correctly.

Best,
Malte

**Comment by jiwonjae** [comment]
Yep, my mistake. The function below should do the job.
``` Python
def create_device(up_pulses, down_pulses, w_min, w_max):
    device = ConstantStepDevice()

    dw_up = (w_max - w_min)/up_pulses
    dw_down = (w_max - w_min)/down_pulses
    dw_min = dw_up if dw_up > dw_down else dw_down
    up_down = (dw_up - dw_down) / dw_min

    device.dw_min, device.dw_min_dtod, device.dw_min_std = dw_min, 0., 0.
    device.up_down, device.up_down_dtod = up_down, 0.
    device.w_max, device.w_max_dtod = w_max, 0.
    device.w_min, device.w_min_dtod = w_min, 0.
    
    return device
```
By the way, I find the docs regarding `up_down` from the `aihwkit.simulator.configs.devices` confusing.

> Up and down direction step sizes can be systematically different and also vary across devices. `\Delta w_{ij}^d` is set during RPU initialization (for each cross-point `ij`)
``\Delta w_{ij}^d = d\; \Delta w_\text{min}\ \left(1 + d \beta_{ij} + \sigma_\text{d-to-d}\xi\right)``
where `\xi` is again a standard Gaussian. `\beta_{ij}` is the directional up `versus` down bias. 
At initialization ``up_down_dtod`` and ``up_down`` defines this bias term: 
``\beta_{ij} = \beta_\text{up-down} + \xi \sigma_\text{up-down-dtod} ``
where `\xi` is again a standard Gaussian number and  `\beta_\text{up-down}` corresponds to ``up_down``. Note that ``up_down_dtod`` is again given in relative units to ``dw_min``.

Thought that `dw_min` should be half of the difference of the amount of `dw_up` and `dw_down`; resulting `dw_up = dw_min*(1+up_down)`, `dw_down = dw_min*(1-up_down)`.

Can we edit the docs to be a bit clearer? Thanks!
