### ISSUE TITLE
Compiling error related to RPU config 

### ISSUE THREAD

**Issue by dongwhfdyer** [IBM/aihwkit#498]
## Description

I have successfully installed in two machines. But in some machines, it failed. 

```
/data/home/pcl/proj/aihwkit/src/rpucuda/rpu_pulsed_device.h:128:3: error: function ‘RPU::PulsedRPUDeviceBase<T>::PulsedRPUDeviceBase(RPU::PulsedRPUDeviceBase<T>&&) [with T = float]’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘RPU::PulsedRPUDeviceBase<float>::PulsedRPUDeviceBase(RPU::PulsedRPUDeviceBase<float>&&)’
```
it's the whole installation log. 

https://drive.google.com/file/d/11thBy6ZjrP8Raw8huUYRjMhF7ibaIIEy/view?usp=sharing

## How to reproduce

I use the following scripts to install. Everyting went well except for the last one. 
```
conda create -n aihwkit python=3.8
conda activate aihwkit
conda install -y cmake openblas pybind11
conda install -y -c conda-forge scikit-build
pip install torch torchvision
git clone https://github.com/IBM/aihwkit.git
cd aihwkit
conda install -y -c intel mkl mkl-devel mkl-static mkl-include
MKLROOT=$CONDA_PREFIX/lib CMAKE_PREFIX_PATH=$CONDA_PREFIX make build_cuda flags="-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DRPU_CUDA_ARCHITECTURES='70'"
```

## Expected behavior

successfully installation

## Other information

* Pytorch version: 2.0
* pip package and conda package: 
[pip list on google drive](https://drive.google.com/file/d/1UiOCFfGXzc1ZkrhBOYpV8xay6tQIk0O_/view?usp=sharing)
[conda list on google drive](https://drive.google.com/file/d/1u4K4wYqZhwnNTF6JHE5ljCiTnnC4l2z0/view?usp=sharing)
* OS: centos 7.9
* Python version: 3.8
* Conda version (or N/A): conda 23.3.1 
* CUDA version: tried 11.7 and 12.1
* GPU version: v100

**Comment by maljoras** [comment]
It seems that your compiler is way too old. You are using gcc 4.8.5.  Please try again with at least 7.x . Current gcc is >11.x .

**Comment by dongwhfdyer** [comment]
I followed your instructions to install gcc 9,10,and 11. I tried all of them. 
But there are still errors related to RPU. 
[installation log on google drive](https://drive.google.com/file/d/1BTESDYcbTer0Z1dV7vXZn-Rzf_T3RIaz/view?usp=sharing)

**Comment by maljoras** [comment]
Hi @dongwhfdyer,
Thanks for updating GCC. Now it looks like an error related to CUB. Could you try again with CUDA 11.7 ? CUDA 12.1 is very new and I am not sure whether even pytorch works with that.

**Comment by dongwhfdyer** [comment]
Really thank you. I thought I tried. Then I tried again. It works!
