### ISSUE TITLE
cannot use the cuda and gpu after compile 

### ISSUE THREAD

**Issue by meicale** [IBM/aihwkit#549]
## How to reproduce

Follow the advanced installation, I build on wsl2_ubuntu 22.04 with torch1.13 and cuda 11.7 , some minor difference is that I use micromamba instead of the conda and "python -m pip" instead of "pip" and I use nix to manage the my config and shell env and it gives me :

[ 98%] Building CXX object src/aihwkit/simulator/CMakeFiles/rpu_base.dir/rpu_base_src/rpu_base_tiles_cuda.cpp.o
[100%] Linking CXX shared module rpu_base.cpython-39-x86_64-linux-gnu.so
......
does it completed? I can run the code but cuda.is_compiled is 0.
I can also run the code after running make clean which make me confused.
## Expected behavior
cuda.is_compiled is 1.

when I run the code it should use the gpu instead of use just cpu. This is because if cuda.is_compiled is 0 the DEVICE is cpu.
## Other information

cuda 11.7 torchvision 1.14
* Pytorch version:1.13.1
* Package version: 0.8
* OS: WSL2_Ubuntu22.04 on Windows11
* Python version: 3.9.18
* Conda version (or N/A): micromamba 1.5.1

**Comment by maljoras** [comment]
Hi @meicale,
can you specify a little more? Please post the full cmake output  during compilation. Did you specify `-DUSE_CUDA=ON` or did use one of the shortcuts `make build_cuda` ?

**Comment by meicale** [comment]
> Hi @meicale, can you specify a little more? Please post the full cmake output during compilation. Did you specify `-DUSE_CUDA=ON` or did use one of the shortcuts `make build_cuda` ?

use a new make sub-command base on build_inplace added with DUSE_CUDA=ON.  I just tried openblas instead of unfree one.  It is compiled, with no error, but I can not use it, kind of wire. I guess it have sth realated with nix with which i used to make my shell. I also try in a new wsl2_ubuntu instance from scratch, and it works, it can compile and using the gpu. but I find the accuracy is quite low at ~20%.
Thanks for your reply.
