### ISSUE TITLE
Discrepancy Between Documentation and Code: AnalogModuleBase

### ISSUE THREAD

**Issue by Zhaoxian-Wu** [IBM/aihwkit#559]
When I was reading the documentation, I noticed an inconsistency between the documentation and the actual code. To be specific, the code in the documentation enables a parameter ``force_exact`` in ``aihwkit.nn.modules.base.AnalogLayerBase`` while that in the Github doesn't. It seems the documentation version is newer. The related links are listed as follows. I wonder whether your team has a plan to update the code to the latest version recently?

Documentation Location: [aihwkit.nn.modules.base](https://aihwkit.readthedocs.io/en/latest/_modules/aihwkit/nn/modules/base.html#AnalogModuleBase.get_weights)

Code Location: [aihwkit.nn.modules.base](https://github.com/IBM/aihwkit/blob/master/src/aihwkit/nn/modules/base.py#L195)

I would appreciate your kind response.

**Comment by maljoras** [comment]
Hi @Zhaoxian-Wu ,
thanks for this issue. It seems that the documentation is out-dated. Certainly the code is the most recent. The `force_exact` is a legacy that was removed a while ago. The keyword is now `realistic=False/True`. See [here](https://github.com/IBM/aihwkit/blob/master/src/aihwkit/simulator/tiles/periphery.py#L172)

**Comment by maljoras** [comment]
@kaoutar55, the documentation sphinx API seems to be out-dated and needs to be rebuild.

**Comment by maljoras** [comment]
see #577
