### ISSUE TITLE
Transfer compound as optimizors

### ISSUE THREAD

**Issue by Zhaoxian-Wu** [IBM/aihwkit#560]
## Description and motivation
Currently, all the transfer manipulations, e.g. fast transfer and slow transfer, in TT-v1 to v4 are implemented in C++. I found it hard to customize my own transfer manipulation if I would like to use Pytorch only. Is it possible to provide some transfer primitives so that all transfer compounds (Transfer, BufferedTransfer, ChoppedTransfer, DynamicTransfer) can be implemented by Python?

I have this question since all of these compounds are the implementations of some concrete algorithms instead of device implementations. In PyTorch style, it is better to implement these algorithms as optimizers. Therefore, it makes sense to implement the device behaviors, like MVM, noise, and pulse update, in C++ since they reflect the device properties. And then expose the interfaces to optimizers, which are responsible for implementing TT family algorithms.

With these Python codes, programmers could be more easy to customize optimizers for analog devices.

## Proposed solution

I guess it is better to abstract all feasible operations of the devices (transfer to other devices, chopper, and so on), encapsulate them in C++, and provide proper interfaces or primitives. After that, implement all transfer compounds (Transfer, BufferedTransfer, ChoppedTransfer, DynamicTransfer) as optimizers.

## Related Issue
As a remark, I found my issue is closely related to issue #221, which asks for manipulation primitives in the analog tile level.

**Comment by maljoras** [comment]
Hi @Zhaoxian-Wu , thanks for raising the issue. 

Note that C++ is used for speed purposes. It is actually quite straightforward for programmers to change and extend the compounds using C++, so the statement of being able to change it in python is a rather a limitation on the side of the user (not being able to code in C++ ) and not of the code itself. The advantage of C++ is that speed is very high for the complicated learning algorithms.  We could provide a python implementation, however, it will be severely speed limiting, and thus might not be useful at all. Of course for experimenting with the algorithm before transferring it to C++ it might be useful.

**Comment by maljoras** [comment]
I have added a partially torch transfer tile in #567 which has some compromise between flexibility and speed. However, in particular if batch sizes are large and transfers are more often than batch size, the speed in torch is too limiting, this the tile does not support these scenarios. However, it could be used to run small test cases when one wants to implement a new learning rule, and then one could port a successful new algorithm to C++ if needed to be able to scale up simulations.

**Comment by Zhaoxian-Wu** [comment]
Thanks for your contribution to the library @maljoras! I understand it's challenging to balance the flexibility and speed, but `TorchTransferTile` seems to be much easier to modify. Thanks for your attention again!
