### ISSUE TITLE
Using analog models in DDP with multiple GPUs causes warnings and errors related to "wrong device"

### ISSUE THREAD

**Issue by jdbuhler** [IBM/aihwkit#565]
## Description

I am attempting to use PyTorch DynamicDataParallelism with a regular PyTorch model that was converted to analog using convert_to_analog_mapped() with an InferenceRPUConfig. After conversion, when I call model.prepare_for_ddp(), I get the following warning from all processes of rank > 0:

"WARNING wrong device detected: 0 vs. 1"

(replace 1 with the rank of the complaining process above). If I checkpoint an analog model by calling pytorch.save() on its state_dict, then reload the checkpoint into a fresh copy of the analog model in each process, I get a fatal error from prepare_for_ddp(), of the form

aihwkit.exceptions.ModuleError: DDP is only supported with shared weights (e.g. InferenceTile)

I tried using TorchInferenceRPUConfig instead of regular InferenceRPUConfig, but doing so even without checkpointing raises the same error as above.

The warning is reproducible for me on example 20 (the DDP example) in the aihwkit examples directory.

## How to reproduce

Run example 20, which uses two GPUs.  The process of rank 1 should display the warning.

## Expected behavior

Analog models created in each DDP process should naturally use the resources associated with that process, with no warning or error.  Saving an analog model created with one device and later reloading its dict into a copy of the copy of the model created on another device  should not cause "wrong device" errors.

## Other information

* Pytorch version: 2.1.0
* Package version: 0.8.0
* OS: Linux x86_64, CUDA 11.8 SDK, 11.2 kernel driver
* Python version: 3.11.5
* Conda version (or N/A): 23.11.0

**Comment by maljoras** [comment]
Hi @jdbuhler,
many thanks for raising the issue, there indeed seems to be a bug somewhere which likely got introduced with some of the recent changes. I will look into this.
