### ISSUE TITLE
CUDA enabled IBM kit Advanced development setup

### ISSUE THREAD

**Issue by adnanrana88** [IBM/aihwkit#579]
## Description
I am facing the issue of compiling the CUDA enabled development env of IBM kit setup in Anaconda. My laptop have GeForce 4060 gpu with Windows 11.
Anyone have already correct version combination of Python, CUDA, Pytorch for GeForce 4060 series gpu. Please share ??

I am creating the Anaconda env like this and then installing all required packages.

@echo off
conda create -n ibm python=3.10 -y
call conda activate ibm
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y
git clone https://github.com/IBM/aihwkit.git
cd aihwkit
conda install -c anaconda openblas -y
conda clean --all -y
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install cmake
conda install scikit-build -y
conda install pybind11 -y
conda install -c intel mkl mkl-devel mkl-static mkl-include -y
conda clean --all -y
python setup.py build_ext --inplace -DUSE_CUDA=ON
echo Running example script...
python examples/01_simple_layer.py

Flowing error comes during cuda enabled build.

(ibm) C:\Users\adnan\aihwkit>python setup.py build_ext --inplace -DUSE_CUDA=ON

--------------------------------------------------------------------------------
-- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is MSVC 19.38.33133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is MSVC 19.38.33133.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (2.4s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/adnan/aihwkit/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    C:\Users\adnan\aihwkit\_skbuild\win-amd64-3.9\cmake-build
  Command:
    'C:\Users\adnan\.conda\envs\ibm\lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\adnan\aihwkit' -G Ninja -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\adnan\aihwkit\_skbuild\win-amd64-3.9\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.9.18 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\adnan\.conda\envs\ibm\lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\adnan\.conda\envs\ibm\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\adnan\.conda\envs\ibm\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\adnan\.conda\envs\ibm\libs\python39.lib' '-DPython_EXECUTABLE:PATH=C:\Users\adnan\.conda\envs\ibm\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\adnan\.conda\envs\ibm' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\adnan\.conda\envs\ibm\Include' '-DPython_LIBRARY:PATH=C:\Users\adnan\.conda\envs\ibm\libs\python39.lib' '-DPython_NumPy_INCLUDE_DIRS:PATH=C:\Users\adnan\.conda\envs\ibm\lib\site-packages\numpy\core\include' '-DPython3_EXECUTABLE:PATH=C:\Users\adnan\.conda\envs\ibm\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\adnan\.conda\envs\ibm' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\adnan\.conda\envs\ibm\Include' '-DPython3_LIBRARY:PATH=C:\Users\adnan\.conda\envs\ibm\libs\python39.lib' '-DPython3_NumPy_INCLUDE_DIRS:PATH=C:\Users\adnan\.conda\envs\ibm\lib\site-packages\numpy\core\include' -DUSE_CUDA=ON -DCMAKE_BUILD_TYPE:STRING=Release

Not searching for unused variables given on the command line.
-- The C compiler identification is MSVC 19.38.33133.0
-- The CXX compiler identification is MSVC 19.38.33133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Invoking cmake through scikit-build
-- The BLAS backend of choice:OpenBLAS
-- Found OpenBLAS libraries: C:/OpenBLAS/lib/libopenblas.lib
-- Found OpenBLAS include: C:/OpenBLAS/include
-- Found Python3: C:/Users/adnan/.conda/envs/ibm/python.exe (found version "3.9.18") found components: Interpreter Development Development.Module Development.Embed
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- Found pybind11: C:/Users/adnan/.conda/envs/ibm/Lib/site-packages/pybind11/include (found version "2.11.1")
-- Found Python: C:/Users/adnan/.conda/envs/ibm/python.exe (found version "3.9.18") found components: Interpreter
-- Found Torch: C:/Users/adnan/.conda/envs/ibm/Lib/site-packages/torch/include;C:/Users/adnan/.conda/envs/ibm/Lib/site-packages/torch/include/torch/csrc/api/include
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include (found version "11.8.89")
-- Configuring done (20.0s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/adnan/aihwkit/_skbuild/win-amd64-3.9/cmake-build
[25/80] Building CXX object CMakeFiles\RPU_CPU.dir\src\rpucuda\weight_remapper.cpp.obj
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(5043): warning C4244: '=': conversion from 'const _Ty' to 'float', possible loss of data
        with
        [
            _Ty=double
        ]
Current versions of packages.

* Pytorch version: 2.1.0
* CUDA version: 11.8
* Package version:
* OS: windows 11
* Python version: 3.10
* Conda version (or N/A):

**Comment by kaoutar55** [comment]
Thanks @adnanrana88 for sharing this issue. Have you tried the installation using WSL on your windows machine using our conda package? 

$ conda install -c conda-forge aihwkit
GPU:

$ conda install -c conda-forge aihwkit-gpu

**Comment by adnanrana88** [comment]
Thanks a lot. WSL based on windows 11, setting for IBM Kit working fine using  gpu GeForce series '40'.
