### ISSUE TITLE
Documentation referring to "aihwkit.simulator.devices" which does not exist

### ISSUE THREAD

**Issue by HeatPhoenix** [IBM/aihwkit#592]
## Description

The documentation on this page: https://aihwkit.readthedocs.io/en/latest/design.html, describing how the AI HW Kit is built refers to a number of modules in each section. The link to the devices section is non-functional, and on further inspection such a module does not seem to exist (any longer?). 

## How to reproduce

The broken link/erroneous referral can be found here: https://aihwkit.readthedocs.io/en/latest/design.html#python-simulator-abstraction-layer

## Expected behavior

Probably a removal of the referral and replacement text with how the new version actually works.

## Other information

I'm not 100% sure if this is where I should be reporting documentation problems, so please close the issue if this isn't the right place. Thanks.

**Comment by kaoutar55** [comment]
Thanks for reporting this. We will fix this issue.

**Comment by kkvtran** [comment]
The correction is included in the PR 601 above.   Let us know if you have any questions.  Thanks.
