### ISSUE TITLE
Erroneous reference to "ADD_NORMAL" in WeightNoiseType

### ISSUE THREAD

**Issue by HeatPhoenix** [IBM/aihwkit#608]
## Description

The noise model `ReRamWan2022NoiseModel` comes with the following recommendation:

```
Note:

    To account for short-term read noise (about 1%) one should additional set the forward.w_noise parameter to about 0.01 (with w_noise_type=WeightNoiseType.ADD_NORMAL)
```
However, `WeightNoiseType` does not contain an entry `ADD_NORMAL`, it does contain `ADDITIVE_CONSTANT` in 0.9.0 (git latest as of writing) (see: https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.parameters.enums.html#aihwkit.simulator.parameters.enums.WeightNoiseType).

## How to reproduce

Try to call `WeightNoiseType.ADD_NORMAL` and set it on an InferenceRPUConfig's forward's `w_noise_type`.

## Expected behavior

More of a documentation/code commenting thing than anything, but would recommend to change it to ADDITIVE_CONSTANT as the entry or the documentation to the opposite.

**Comment by maljoras** [comment]
@HeatPhoenix that is correct, it should refer to WeightNoiseType.ADDITIVE_CONSTANT in the documentation (which is same as ADD_NORMAL for the WeightModifierType algorithmically). Would be great of you could open a PR to correct this.

**Comment by maljoras** [comment]
@kkvtran @kaoutar55 maybe you could correct this typo in one of the next PRs?
