### ISSUE TITLE
fusion_import function modifies the input model with the new conductance data

### ISSUE THREAD

**Issue by kkvtran** [IBM/aihwkit#613]
## Description

fusion_import function applied the input conductance data directly on the input model.  Thus modify the input model.

## How to reproduce

programmed_model = fusion_import(Programmed_csv, model, state_dict=state_dict, g_converter=g_converter)

## Expected behavior

 Expect the input model stay in tact and the return model would have the new conductance data.

## Other information

do the deepcopy(model) and apply conductance data to the copied model.

* Pytorch version:  2.1.1
* Package version:  0.9.0
* OS:  linux
* Python version:  3.10
* Conda version (or N/A):  23.7.3

**Comment by maljoras** [comment]
@kkvtran, I don't think this is a bug. It should be inplace no? For larger models it is not feasible to make a copy.  We could add a sentence in the documentation saying that the function is inplace. One can always use deepcopy as you say if that is not intended.

**Comment by maljoras** [comment]
@kkvtran Should we close this issue?

**Comment by maljoras** [comment]
I am closing this issue. Please re-open if needed
