### ISSUE TITLE
Per-Column Weight Scaling

### ISSUE THREAD

**Issue by coreylammie** [IBM/aihwkit#688]
## Description and motivation

@maljoras there does not appear to be a "true" per-column weight scaling scheme: https://github.com/IBM/aihwkit/blob/master/src/aihwkit/simulator/parameters/enums.py#L250-L265 currently available. Could you please confirm this? I think it would make sense to add one if there is not one already.

**Comment by maljoras-sony** [comment]
Hi @coreylammie,
not sure what you mean by "true" per column weight scaling. What you are referring to is the clipping. The column-wise scaling is done with another mechanism, which is enabled here: https://github.com/IBM/aihwkit/blob/master/src/aihwkit/simulator/parameters/mapping.py#L59. This weight scales can be learned with SGD and also re-mapped to the conductances, if necessary, see https://github.com/IBM/aihwkit/blob/39581ece330e989fca59bf18a55f48d159ca29c9/src/aihwkit/simulator/parameters/enums.py#L277. 

So there is a per-column weight scaling scheme already implemented. Is this what you are referring to?
