### ISSUE TITLE
ImportError: cannot import name 'AnalogSGD'

### ISSUE THREAD

**Issue by Mark-314** [IBM/aihwkit#73]
## Description
Traceback (most recent call last):
  File "examples/1_simple_layer.py", line 25, in <module>
    from aihwkit.optim import AnalogSGD
ImportError: cannot import name 'AnalogSGD'

## How to reproduce
I tried both 
python examples/1_simple_layer.py
python3 examples/1_simple_layer.py

/home/zzzzzz/venv/aihwkit_env/git/aihwkit

## Other information

* Pytorch version: 1.6
* Package version: 0.2.0
* OS: Ubuntu 20.04
* Python version: 3.6.9
* Conda version (or N/A):

**Comment by maljoras** [comment]
@Mark-314 thank you for reporting! 

Please take a look at the recently opened Issue #65 and the responses, since it seems to describe the identical problem (see [here]( https://github.com/IBM/aihwkit/issues/65#issuecomment-722969355))

**Comment by diego-plan9** [comment]
Closing the issue after a few days have passed - as mentioned by Malte, please refer to https://github.com/IBM/aihwkit/issues/65#issuecomment-722969355 or reopen if needed.
