### ISSUE TITLE
Error encountered when: Trying to import aihwkit inside Jupyter Notebook

### ISSUE THREAD

**Issue by jhu960213** [IBM/aihwkit#78]
## Description

Hello, from my last comment about the jupyter notebook in a few previous issues ago I said I would post about the Jupyter notebook error with aihwkit. Please see the attached output below. 

<img width="1662" alt="Screen Shot 2020-11-16 at 1 26 35 PM" src="https://user-images.githubusercontent.com/20133323/99292824-c46c8980-280f-11eb-977d-4d25bdf5a9a0.png">

## How to reproduce

So basically, I've followed the advanced and development guides in starting the virtual environment for building aihwkit from scratch and that works (with conda managing the dependencies). But now I would like to run the example codes in Jupyter Notebook but now I'm getting an aihwkit import error (Symbol not found). 

python3 -m venv aihwkit_env
cd aihwkit_env/
source bin/activate
cd aihwkit
git clone https://github.com/IBM/aihwkit.git

*** So after I've done the above steps and installed the dependencies with conda (conda activated also) and build the aihwkit with setup.py I started a Jupyter Notebook and put that notebook inside the "aihwkit" folder (where the python venv and conda environment are). Then after trying to run the example code I get the import error. 

***Note: I have both conda activated and python venv activated within this folder (aihwkit_env)***

Is there a path I'd have to set for the Jupyter Notebook? 

## Expected behavior

The expected behavior is that Is should be able to run the code with no problem as I have already built the project from scratch with setup.py 

## Other information

* Pytorch version: 1.60
* Package version: aihwkit 0.2.0
* OS: OSX 10.15.7
* Python version: 3.8.6
* Conda version (or N/A): 4.9.2

**Comment by jhu960213** [comment]
@diego-plan9 Do you know what's going on?

**Comment by diego-plan9** [comment]
It seems to boil down to making `jupyter` aware of where the package lives - there are a couple of scenarios:
1. if using a ["developer install"](https://aihwkit.readthedocs.io/en/latest/developer_install.html), the process concludes with `python setup.py build_ext --inplace` and the package is _not_ installed from pip's perspective. We recommend this approach when intending to make changes to the source code, as it avoids having to reinstall every time a change in the source code is made - the drawback is that it involves manual handling of `PYTHONPATH`.
2. if using an ["advanced install"](https://aihwkit.readthedocs.io/en/latest/advanced_install.html), the process concludes with the package being installed from pip's perspective. This makes it discoverable by pip and the rest of the tools (including jupyter) in the same way as any other package, but makes it more tedious to try new changes in the source code.

I'm inferring your case is more similar to 1 - if that is the case, it might be just a matter of how jupyter is invoked. Assuming (and from your replies on #65 seems like a safe assumption!) you managed to compile and are able to execute the examples, can you try from the root folder of the cloned repo (and inside an activated virtualenv/conda env):

```
$ PYTHONPATH=/src jupyter notebook
```

That would be akin to "starting jupyter, instructing the Python interpreter used to invoke jupyter to look into `src/` when importing modules". If that is successful (and if you find that pre-pending that string to all your usual commands gets cumbersome), you can make the modification to `PYTHONPATH` a bit more permanent by doing:
```
$ export PYTHONPATH=/path/to/your/cloned_repo/src/
```
This would set the environment variable for all the commands you issue in that terminal. 

If that does not work or you are unable to control how jupyter is launched, there are some workarounds tackling the issue from a different angle - ie. inside Juypter. Within your notebook, you can add a cell at the top with a content similar to:
```python
import sys
sys.path.append("/path/to/your/cloned_repo/src/")
```

Which can be made more generic by [tweaking your jupyter config](https://stackoverflow.com/a/50305652). However, this workaround tends not to be too portable and I'd recommend trying to solve it via correctly setting the python path - let's see if the first approach yields good results in your environment!

**Comment by diego-plan9** [comment]
Closing as the issue has been inactive for a while: please reopen if needed.
