### ISSUE TITLE
Provide pre-built conda package

### ISSUE THREAD

**Issue by diego-plan9** [IBM/aihwkit#93]
## Description and motivation

In the same way we provide `pip` wheels, it would be great to also provide `conda` packages for each release, for convenience to end users. This continues the work in #21 and might be able to help closing #58 (as in ironing out and testing further).

## Proposed solution

Currently depend on two packages that are not in the main anaconda channel (`pytorch` and `scikit-build`). We should find out if it is possible to contribute to [conda-forge](https://conda-forge.org/) and follow its procedures, which is incidentally the channel where `scikit-build` is available (and it seems that there is also a `pytorch` recipe, although lagging behind the official channel quite a bit).

## Alternatives and other information

If depending on channels outside `conda-forge` is not an option, an alternative might be to register our own channel, although that might be a bit too far fetched. Another alternative would be including a base `meta.yaml` in this repository along with instructions on how to build the package manually.

**Comment by maljoras** [comment]
`aihwkit` and `aihgwkit-gpu` Conda-forge  package is now available.
